pagina_ayuda:
    pattern:     /ayuda
    defaults:  { template: 'OfertaBundle:Sitio:ayuda.html.twig' }
    
pagina_privacidad:
    pattern:     /privacidad
    defaults:  { template: 'OfertaBundle:Sitio:privacidad.html.twig' }
    
pagina_condiciones:
    pattern:     /terminos-y-condiciones
    defaults:  { template: 'OfertaBundle:Sitio:terminos-y-condiciones.html.twig' }