parameters:
#    alimento.example.class: Trab\AlimentoBundle\Example

services:
#    alimento.example:
#        class: %alimento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
